---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:

- name: centos-5.10
  driver_config:
    box: opscode-centos-5.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.10_chef-provisionerless.box

- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.5_chef-provisionerless.box

- name: fedora-19
  driver_config:
    box: opscode-fedora-19
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_fedora-19_chef-provisionerless.box

- name: debian-7.4
  driver_config:
    box: opscode-debian-7.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.4_chef-provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-13.10
  driver_config:
    box: opscode-ubuntu-13.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.10_chef-provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[build-essential]
